## 0. Importamos las librerias que vamos a usar

In [1]:
import pandas as pd
import numpy as np
import os

## 1. Unificación previa de tablas antes de la exploración

In [2]:
# 1. Antes de explorar los datos, vamos a unir tablas de la misma categoria para no explorar 16 tablas manualmente

# 1.1 Recoger todos los dataframes de la carpeta 0_raw
ruta = "../Data/0_raw/"
archivos = os.listdir(ruta) # Lista con los nombres de nuestros csv en 0_raw

dfs_raw = {} # Diccionario vacio que contendra todos los df en crudo

for archivo in archivos:
    nombre = archivo.replace(".csv", "") # Quitamos .csv para recoger solo el nombre y usarlo como clave del diccionario
    dfs_raw[nombre] = pd.read_csv(ruta + archivo) # Cargamos el archivo CSV real usando su nombre exacto y lo guardamos en el diccionario.

In [3]:
# 1.2 Unir los dataframes de la misma categoria

# 1.2.1 Deuda
deuda = pd.concat([
    dfs_raw['deuda2009'],
    dfs_raw['deuda2010'],
    dfs_raw['deuda2011']],
    ignore_index= True
)

deuda # Podemos previsualizar que las fechas del 2009 no se estan viendo porque no existe la columna Fecha en 2009

,Países,Deuda total (M.€),Deuda total (M.€).1,Deuda total (M.$),Deuda total (M.$).1,Deuda (%PIB),Deuda Per Cápita,Deuda Per Cápita.1,Fecha
0,España [+],569.535,NaN,793.515,NaN,"53,10%",12.252 €,17.070 $,NaN
1,Alemania [+],1.804.696,NaN,2.514.425,NaN,"72,40%",22.062 €,30.738 $,NaN
2,Reino Unido [+],1.101.852,NaN,1.571.901,NaN,"63,20%",17.627 €,25.146 $,NaN
3,Francia [+],1.627.182,NaN,2.267.126,NaN,"84,10%",25.166 €,35.063 $,NaN
4,Italia [+],1.839.806,NaN,2.563.332,NaN,"116,10%",30.823 €,42.944 $,NaN
...,...,...,...,...,...,...,...,...,...
567,Samoa [+],222,NaN,309,NaN,"41,53%",1.188 €,1.653 $,2011.0
568,Yemen [+],10.752,NaN,14.964,NaN,"45,73%",390 €,543 $,2011.0
569,Sudáfrica [+],114.510,NaN,159.365,NaN,"34,74%",2.190 €,3.048 $,2011.0
570,Zambia [+],3.507,NaN,4.880,NaN,"20,81%",243 €,338 $,2011.0
571,Zimbabue [+],3.617,NaN,2,NaN,"30,02%",290 €,0 $,2011.0

In [4]:
# 1.2.2 Paro
paro = pd.concat([
    dfs_raw['paro2009'],
    dfs_raw['paro2010'],
    dfs_raw['paro2011']],
    ignore_index= True
)

paro

,Países,Tasa de desempleo,Tasa de desempleo.1,Var.,Var. Año,Mes
0,España [+],"18,9%",NaN,020,410,Diciembre 2009
1,Alemania [+],"7,2%",NaN,0,010,Diciembre 2009
2,Reino Unido [+],"7,7%",NaN,-010,120,Diciembre 2009
3,Francia [+],"9,5%",NaN,-010,150,Diciembre 2009
4,Italia [+],"8,5%",NaN,020,160,Diciembre 2009
...,...,...,...,...,...,...
132,Türkiye [+],"8,5%",NaN,010,-160,Diciembre 2011
133,Uruguay [+],"5,6%",NaN,-025,-011,Diciembre 2011
134,Venezuela [+],"6,5%",NaN,030,0,Diciembre 2011
135,Sudáfrica [+],"23,8%",NaN,0,-010,Diciembre 2011
136,< Tasa de desempleo 2010Tasa de desempleo 2012 >,< Tasa de desempleo 2010Tasa de desempleo 2012 >,< Tasa de desempleo 2010Tasa de desempleo 2012 >,< Tasa de desempleo 2010Tasa de desempleo 2012 >,< Tasa de desempleo 2010Tasa de desempleo 2012 >,< Tasa de desempleo 2010Tasa de desempleo 2012 >

In [5]:
# 1.2.3 pib_per_capita
ppcapita = pd.concat([
    dfs_raw['pib_per_capita2009'],
    dfs_raw['pib_per_capita2010'],
    dfs_raw['pib_per_capita2011']],
    ignore_index= True
)

ppcapita

,Países,Fecha,PIB Per Capita,PIB Per Capita.1,PIB Per Capita.2,PIB Per Capita.3,Var. anual PIB Per Capita,Var. anual PIB Per Capita.1,Var. anual PIB Per Capita.2,Var. anual PIB Per Capita.3
0,España [+],2009,23.140 €,NaN,32.159 $,NaN,"-4,3%",NaN,"-9,1%",NaN
1,Alemania [+],2009,30.990 €,NaN,43.174 $,NaN,"-3,3%",NaN,"-8,4%",NaN
2,Reino Unido [+],2009,27.920 €,NaN,39.159 $,NaN,"-13,5%",NaN,"-18,7%",NaN
3,Francia [+],2009,30.040 €,NaN,41.943 $,NaN,"-3,2%",NaN,"-8,3%",NaN
4,Italia [+],2009,26.600 €,NaN,37.143 $,NaN,"-4,2%",NaN,"-9,3%",NaN
...,...,...,...,...,...,...,...,...,...,...
589,Yemen [+],2011,853 €,NaN,1.186 $,NaN,"-2,1%",NaN,"2,7%",NaN
590,Sudáfrica [+],2011,6.304 €,NaN,8.773 $,NaN,"3,2%",NaN,"8,3%",NaN
591,Zambia [+],2011,1.167 €,NaN,1.625 $,NaN,"6,7%",NaN,"12,0%",NaN
592,Zimbabue [+],2011,1.161 €,NaN,1.616 $,NaN,"10,1%",NaN,"15,5%",NaN
593,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,NaN,NaN,NaN,NaN

In [6]:
# 1.2.4 poblacion
poblacion = pd.concat([
    dfs_raw['poblacion2009'],
    dfs_raw['poblacion2010'],
    dfs_raw['poblacion2011']],
    ignore_index= True
)

poblacion

              Países  Densidad   Población  Población.1    Var.   Año
0         España [+]      92.0  46.486.621          NaN   0,26%  2009
1       Alemania [+]     229.0  81.802.257          NaN  -0,24%  2009
2    Reino Unido [+]     257.0  62.510.197          NaN   0,75%  2009
3        Francia [+]     118.0  64.658.856          NaN   0,48%  2009
4         Italia [+]     198.0  59.690.316          NaN   0,45%  2009
..               ...       ...         ...          ...     ...   ...
583        Samoa [+]      66.0     187.000          NaN   0,54%  2011
584        Yemen [+]      52.0  27.583.000          NaN   3,10%  2011
585    Sudáfrica [+]      43.0  52.285.000          NaN   1,51%  2011
586       Zambia [+]      19.0  14.438.000          NaN   3,38%  2011
587     Zimbabue [+]      32.0  12.459.000          NaN   0,96%  2011

[588 rows x 6 columns]

In [7]:
# 1.2.6 pib
pib = pd.concat([
    dfs_raw['pib2009'],
    dfs_raw['pib2010'],
    dfs_raw['pib2011']],
    ignore_index= True
)

pib

,Países,Fecha,PIB anual,PIB anual.1,PIB anual.2,PIB anual.3,Var. PIB (%),Var. PIB (%).1
0,España [+],2009,1.072.990 M€,NaN,1.496.588 M$,NaN,"-3,8%",NaN
1,Alemania [+],2009,2.493.970 M€,NaN,3.478.546 M$,NaN,"-5,5%",NaN
2,Reino Unido [+],2009,1.738.067 M€,NaN,2.429.285 M$,NaN,"-4,1%",NaN
3,Francia [+],2009,1.935.840 M€,NaN,2.700.076 M$,NaN,"-2,8%",NaN
4,Italia [+],2009,1.584.107 M€,NaN,2.209.484 M$,NaN,"-5,3%",NaN
...,...,...,...,...,...,...,...,...
589,Yemen [+],2011,23.515 M€,NaN,32.726 M$,NaN,"-12,7%",NaN
590,Sudáfrica [+],2011,329.600 M€,NaN,458.199 M$,NaN,"3,2%",NaN
591,Zambia [+],2011,16.853 M€,NaN,23.455 M$,NaN,"5,6%",NaN
592,Zimbabue [+],2011,14.467 M€,NaN,20.134 M$,NaN,"14,2%",NaN
593,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,< PIB 2010PIB 2012 >,NaN,NaN

In [8]:
# 1.2.6 online_retail_II (archivo en bruto descargado de Kaggle)
retail = pd.read_csv('../Data/0_raw/online_retail_II.csv')
retail

# Nota: El dataset de retail tiene los países en inglés, mientras que los datos macroeconómicos están en español.
# Para poder hacer un merge correcto en la fase de limpieza, será necesario traducir los países de los datos macro al inglés.

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

### 1.3 Mandar los datos a la carpeta Interim

In [9]:
deuda.to_csv('../Data/1_interim/deuda.csv', index = False)
paro.to_csv('../Data/1_interim/paro.csv', index = False)
poblacion.to_csv('../Data/1_interim/poblacion.csv', index = False)
pib.to_csv('../Data/1_interim/pib.csv', index = False)
ppcapita.to_csv('../Data/1_interim/ppcapita.csv', index = False)
retail.to_csv('../Data/1_interim/retail.csv', index = False)

## 2. Exploración

Tenemos **6 archivos** para explorar:

- **deuda**
- **paro**
- **población**
- **pib**
- **ppcapita**
- **retail**

In [10]:
# 2.1 Deuda

deuda.info()
# - Eliminar columnas: 'Deuda total (M.€).1', 'Deuda total (M.$)',
#   'Deuda total (M.$).1' y 'Deuda Per Cápita.1'.
# - Convertir a tipo numérico: 'Deuda total (M.€)', 'Deuda (%PIB)' y
#   'Deuda Per Cápita'.
# - Convertir 'Fecha' en 'Año' a numerico.

deuda.sample(5)
# - La columna 'Fecha' tiene NaN para 2009 porque la tabla original no
#   incluía el año. Se imputará el valor 2009.
# - Traducir los nombres de los países y eliminar el sufijo '[+]'
#   para que coincidan con el DataFrame 'retail'.

deuda.describe(include='all')
# - Se confirma que algunas columnas tienen tipos de datos incorrectos.

deuda.isna().sum()
# - Los únicos NaN relevantes corresponden a la columna 'Fecha'.
# - El resto pertenecen a columnas que se eliminarán.

deuda.duplicated().sum()
# - Existe una fila duplicada que deberá eliminarse.

deuda[deuda.duplicated(keep=False)]
# - Visualización de la fila duplicada.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Países               572 non-null    object
 1   Deuda total (M.€)    572 non-null    object
 2   Deuda total (M.€).1  0 non-null      float64
 3   Deuda total (M.$)    572 non-null    object
 4   Deuda total (M.$).1  0 non-null      float64
 5   Deuda (%PIB)         572 non-null    object
 6   Deuda Per Cápita     572 non-null    object
 7   Deuda Per Cápita.1   572 non-null    object
 8   Fecha                382 non-null    float64
dtypes: float64(3), object(6)
memory usage: 40.3+ KB

,Países,Deuda total (M.€),Deuda total (M.€).1,Deuda total (M.$),Deuda total (M.$).1,Deuda (%PIB),Deuda Per Cápita,Deuda Per Cápita.1,Fecha
352,Siria [+],12.083,NaN,16.835,NaN,"31,21%",573 €,798 $,2009.0
544,Siria [+],12.083,NaN,16.835,NaN,"31,21%",573 €,798 $,2009.0

In [11]:
# 2.2 Paro

paro.info()
# - Eliminar las columnas: 'Tasa de desempleo.1', 'Var.' y 'Var. Año'.
# - Convertir 'Tasa de desempleo' a tipo numérico.
# - Renombrar la columna 'Mes' a 'Año' y convertirla a tipo int.

paro.sample(5)
paro["Mes"].value_counts()
# - Eliminar algunas filas que se han colado en el scrapeo.
# - Extraer el año de la columna 'Mes', renombrarla a 'Año' y convertirla a int.
# - Eliminar el sufijo '[+]' de los nombres de los países.

paro.describe(include="all")
# - Se confirma que es necesario realizar la limpieza para obtener un resumen
#   estadístico correcto.

paro.isna().sum()
# - Los únicos valores nulos pertenecen a columnas que serán eliminadas
#   ('Tasa de desempleo.1' y 'Var. Año').

paro.duplicated().sum()
# - No existen filas duplicadas.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Países               137 non-null    object
 1   Tasa de desempleo    137 non-null    object
 2   Tasa de desempleo.1  3 non-null      object
 3   Var.                 137 non-null    object
 4   Var. Año             136 non-null    object
 5   Mes                  137 non-null    object
dtypes: object(6)
memory usage: 6.6+ KB

np.int64(0)

In [12]:
# 2.3 Poblacion

poblacion.info()
# - Eliminaremos columnas como: 'Densidad', 'Población.1' y 'Var.'
# - Cambiaremos el tipo de datos a int de la columna 'Población'

poblacion.sample(5)
# - Eliminar el sufijo '[+]' de los nombres de los países.


poblacion.describe(include="all")
# - Se confirma que es necesario realizar la limpieza para obtener un resumen
#   estadístico correcto.

poblacion.isna().sum()
# - La unica columna que tiene nulos va a ser eliminada porque no la necesitamos

poblacion.duplicated().sum()
# - No hay presencia de duplicados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Países       588 non-null    object
 1   Densidad     588 non-null    float64
 2   Población    588 non-null    object
 3   Población.1  0 non-null      float64
 4   Var.         588 non-null    object
 5   Año          588 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 27.7+ KB

np.int64(0)

In [13]:
# 2.4 PIB

pib.info()
# - Eliminar las columnas: 'PIB anual.1', 'PIB anual.2', 'PIB anual.3',
#   'Var. PIB (%)' y 'Var. PIB (%).1'.
# - Renombrar la columna 'Fecha' a 'Año' y convertirla a tipo int.
# - Convertir 'PIB anual' a tipo numérico, eliminando previamente los
#   caracteres que podrían impedir la conversión

pib.sample(5)
# - Eliminar el sufijo '[+]' de los nombres de los países.

pib.describe(include="all")
# - Se confirma que es necesario realizar la limpieza para obtener un
#   resumen estadístico correcto.

pib["Países"].value_counts()
# - Eliminar las filas que contienen texto y no corresponden a países,
#   por ejemplo: '< PIB 2008' o 'PIB 2010 >'.

pib.isna().sum()
# - Las columnas 'PIB anual.1', 'PIB anual.3', 'Var. PIB (%)' y
#   'Var. PIB (%).1' contienen valores nulos, pero no es necesario
#   tratarlos porque dichas columnas serán eliminadas.

pib.duplicated().sum()
# - No existen filas duplicadas.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Países          594 non-null    object
 1   Fecha           594 non-null    object
 2   PIB anual       594 non-null    object
 3   PIB anual.1     3 non-null      object
 4   PIB anual.2     594 non-null    object
 5   PIB anual.3     3 non-null      object
 6   Var. PIB (%)    591 non-null    object
 7   Var. PIB (%).1  0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 37.3+ KB

np.int64(0)

In [14]:
# 2.5 ppcapita

ppcapita.info()
# - Cambiar nombre de Fecha a Año y su tipo de datos a int
# - Nos quedamos solo con las columnas: 'Países', 'Año', 'PIB Per Capita'
# - Cambiar el tipo de datos de PIB Per Capita a int

ppcapita.sample(5)
# - Quitar el sufijo [+] de los paises.

ppcapita.describe(include="all")
# - Se confirma que es necesario realizar la limpieza para obtener un
#   resumen estadístico correcto.

ppcapita["Países"].value_counts()
# - Eliminar las filas que contienen texto y no corresponden a países,
#   por ejemplo: '< PIB 2008PIB 2010 >'.

ppcapita.isna().sum()
# - Tenemos nulos en varias columnas. Pero son nulos de columnas que vamos a eliminar


ppcapita.duplicated().sum()
# - No tenemos duplicados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Países                       594 non-null    object
 1   Fecha                        594 non-null    object
 2   PIB Per Capita               594 non-null    object
 3   PIB Per Capita.1             3 non-null      object
 4   PIB Per Capita.2             594 non-null    object
 5   PIB Per Capita.3             3 non-null      object
 6   Var. anual PIB Per Capita    591 non-null    object
 7   Var. anual PIB Per Capita.1  0 non-null      float64
 8   Var. anual PIB Per Capita.2  591 non-null    object
 9   Var. anual PIB Per Capita.3  0 non-null      float64
dtypes: float64(2), object(8)
memory usage: 46.5+ KB

np.int64(0)

In [15]:
# 2.6 retail

retail.info()
# - Revisamos la estructura del dataset para detectar tipos incorrectos y códigos mixtos.
# - InvoiceNo y StockCode se mantienen como object porque las letras contienen información útil.
# - InvoiceDate se usará para crear una jerarquía temporal (año, mes, día) para análisis y merge.
# - CustomerID se convertirá a int para permitir segmentación y análisis por cliente.
# - Evaluaremos la creación de columnas derivadas (IsCancelled, Variant) sin perder información.

retail.sample(5)
# - Nos damos cuenta que no solo tenemos ventas, tambien tenemos movimientos internos del almacen
# con descripciones, customer id, cantidades y precios que sesgan nuestro analisis puramente de ventas

retail.describe().T
# - Quantity presenta valores negativos → devoluciones.
# - Quantity y Price tienen valores extremadamente altos (hasta 80k y 38k) → outliers que requieren revisión.
# - Price negativo → ajustes contables o devoluciones.
# - La presencia de outliers confirma que será necesaria una limpieza cuidadosa antes del análisis final.

retail.isna().sum()
# - Tenemos 243007 valores nulos en customer id que deberemos tratar o imputar
# - Tenemos 4382 valores nulos en description, deberemos imputar con "Sin descripcion"

retail["Country"].value_counts()
# - Necesario para obtener la traduccion de los paises para la posterior traduccion y el merge

retail.duplicated().sum()
# - Tenemos 34335 duplicados, que eliminaremos en la limpieza

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

np.int64(34335)