## 0. Importamos las librerias que vamos a utilizar

In [181]:
import pandas as pd
import numpy as np

### 0.1 Importamos los dataframes para limpiarlos

In [182]:
deuda = pd.read_csv('../Data/1_interim/deuda.csv')
paro = pd.read_csv('../Data/1_interim/paro.csv')
pib = pd.read_csv('../Data/1_interim/pib.csv')
poblacion = pd.read_csv('../Data/1_interim/poblacion.csv')
ppcapita = pd.read_csv('../Data/1_interim/ppcapita.csv')
retail = pd.read_csv('../Data/1_interim/retail.csv')

## 1. Limpieza

### 1.1 Deuda

In [183]:
# Eliminar columnas que no necesitamos
deuda.drop(columns = ['Deuda total (M.€).1', 'Deuda total (M.$)', 'Deuda total (M.$).1', 'Deuda Per Cápita.1'], inplace = True)

In [184]:
# Cambiar nombre de la columna Fecha a Año
deuda.rename(columns= {'Fecha' : 'Year'}, inplace = True)

# Imputar valor 2009 en los años con NaN segun se vio en limpieza
deuda['Year'] = deuda['Year'].fillna(2009)

In [185]:
# Cambiar tipo de datos

# Convertir Año a entero
deuda['Year'] = deuda['Year'].astype(int)

# Convertir Deuda total (M.€) y Deuda Per Cápita a int (formato correcto)
cols = ['Deuda total (M.€)', 'Deuda Per Cápita']

for c in cols:
    deuda[c] = (
        deuda[c]
        .str.replace('.', '', regex=False)
        .str.replace(',', '.', regex=False)
        .str.replace('€', '', regex=False)
    )
    deuda[c] = deuda[c].astype(int)

# Convertir Deuda (%PIB) a float (formato correcto)

deuda['Deuda (%PIB)'] = (
    deuda['Deuda (%PIB)']
    .str.replace(',','.', regex = False)
    .str.replace('%', '', regex = False)
    .astype(float)
    .round(2)
)

In [186]:
# Arreglar columna de Países
deuda.rename(columns= {'Países' : 'Country'}, inplace = True)
deuda['Country'] = deuda['Country'].str.replace(' [+]', '')

pd.set_option('display.max_rows', None)
deuda['Country'].value_counts()

deuda.info()

<class 'pandas.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            572 non-null    str
 1   Deuda total (M.€)  572 non-null    int64
 2   Deuda (%PIB)       572 non-null    float64
 3   Deuda Per Cápita   572 non-null    int64
 4   Year               572 non-null    int64
dtypes: float64(1), int64(3), str(1)
memory usage: 22.5 KB

### 1.2 Paro

In [187]:
# Eliminar columnas que no necesitamos
paro.drop(columns = ['Tasa de desempleo.1', 'Var.', 'Var. Año'], inplace = True)

In [188]:
# Cambiar nombre de la columna Fecha a Año
paro.rename(columns= {'Mes' : 'Year'}, inplace = True)

paro['Year'] = paro['Year'].str.replace('Diciembre ', '')
paro['Year'].value_counts()

Year
2010                                                45
2011                                                45
2009                                                44
< Tasa de desempleo 2008Tasa de desempleo 2010 >     1
< Tasa de desempleo 2009Tasa de desempleo 2011 >     1
< Tasa de desempleo 2010Tasa de desempleo 2012 >     1
Name: count, dtype: int64

In [189]:
# Cambiar tipo de datos
paro.head()

# Cambiar a float la Tasa de desempleo
paro['Tasa de desempleo'] = (
    paro['Tasa de desempleo']
    .str.replace(',', '.')
    .str.replace('%', '')
)

# Usando errors coerce convertimos en nan todo lo que no se puede convertir en numerico, gracias a pd.to_numeric. Astype() no puede hacerlo
paro['Tasa de desempleo'] = pd.to_numeric(paro['Tasa de desempleo'], errors='coerce')

# Convertir año en float, para usar errors = coerce
paro['Year'] = pd.to_numeric(paro['Year'], errors='coerce')

# Borrar las filas que scrapearon valores incorrectos
paro.info()
paro = paro.dropna() # Conseguimos eliminar esos 3 valores gracias errors = coerce que convirtio en nulos los valores que no cumplían con el tipo

# Convertir Year en int
paro['Year'] = paro['Year'].astype(int)

<class 'pandas.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Países             137 non-null    str
 1   Tasa de desempleo  134 non-null    float64
 2   Year               134 non-null    float64
dtypes: float64(2), str(1)
memory usage: 3.3 KB

In [190]:
# Arreglar columna de Países
paro.rename(columns= {'Países' : 'Country'}, inplace = True)
paro['Country'] = paro['Country'].str.replace(' [+]', '')

paro['Country'].value_counts()

paro.info()

<class 'pandas.DataFrame'>
Index: 134 entries, 0 to 135
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            134 non-null    str
 1   Tasa de desempleo  134 non-null    float64
 2   Year               134 non-null    int64
dtypes: float64(1), int64(1), str(1)
memory usage: 4.2 KB

### 1.3 PIB

In [191]:
# Eliminar columnas que no necesitamos
pib.drop(columns = ['PIB anual.1', 'PIB anual.2', 'PIB anual.3', 'Var. PIB (%)', 'Var. PIB (%).1'], inplace = True)

# Cambiar nombre a la columna Fecha
pib.rename(columns = {'Fecha': 'Year'}, inplace= True)
pib.rename(columns = {'Países': 'Country'}, inplace= True)

In [192]:
# Cambiar el tipo de datos y corregir formato
## 1º Cambiar el nombre de la columna
pib = pib.rename(columns = {'PIB anual' : 'PIB anual (M€)'})

pib['PIB anual (M€)'].head().apply(repr) # repr(x) devuelve la representación literal del objeto tal como Python lo ve internamente.

## 2º Cambiar el valor de los datos
pib['PIB anual (M€)'] = (
    pib['PIB anual (M€)']
    .str.replace('\xa0', '', regex=False)     # elimina el espacio raro
    .str.replace('.', '', regex=False)        # elimina puntos de miles
    .str.replace('M€', '', regex=False)       # elimina la unidad
    .str.strip()                              # elimina espacios normales
)

pib['Country'] = pib['Country'].str.replace(' [+]', '', regex = False)

# 3º Forzar com error = coerce para luego eliminar las filas mal scrapeadas
pib['PIB anual (M€)'] = pd.to_numeric(pib['PIB anual (M€)'], errors='coerce')

# 4º Eliminar filas mal scrapeadas
pib = pib.dropna()

# 5º Cambiar tipo de datos
pib['PIB anual (M€)'] = pib['PIB anual (M€)'].astype(int)
pib['Year'] = pib['Year'].astype(int)

In [193]:
pib.info()

<class 'pandas.DataFrame'>
Index: 591 entries, 0 to 592
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         591 non-null    str
 1   Year            591 non-null    int64
 2   PIB anual (M€)  591 non-null    int64
dtypes: int64(2), str(1)
memory usage: 18.5 KB

### 1.4 Poblacion

In [194]:
poblacion.head()

# Eliminar columnas
poblacion.drop(columns = ['Densidad', 'Población.1', 'Var.'], inplace = True)
poblacion.rename(columns = {'Año': 'Year'}, inplace= True)

In [195]:
# Cambiar tipo de datos y arreglar formato
poblacion['Población'] = (
    poblacion['Población']
    .str.replace('.', '')
    .astype(int)
)

# Arreglar paises
poblacion.rename(columns = {'Países': 'Country'}, inplace= True)
poblacion['Country'] = poblacion['Country'].str.replace(' [+]','')
poblacion.head()

       Country  Población  Year
0       España   46486621  2009
1     Alemania   81802257  2009
2  Reino Unido   62510197  2009
3      Francia   64658856  2009
4       Italia   59690316  2009

In [196]:
poblacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    588 non-null    str
 1   Población  588 non-null    int64
 2   Year       588 non-null    int64
dtypes: int64(2), str(1)
memory usage: 13.9 KB

### 1.5 PIB Per Capita

In [197]:
# Eliminar columnas que no necesitamos
ppcapita.drop(columns = ['PIB Per Capita.1', 'PIB Per Capita.2', 'PIB Per Capita.3', 'Var. anual PIB Per Capita', 'Var. anual PIB Per Capita.1','Var. anual PIB Per Capita.2','Var. anual PIB Per Capita.3'], inplace = True)

In [198]:
# Renombrar columnas
ppcapita.rename(columns={
    'Fecha': 'Year',
    'PIB Per Capita' : 'PIB Per Capita (€)',
    'Países' : 'Country'
}, inplace = True)

In [199]:
# Cambiar formato de los datos para poder cambiar su tipo de datos
ppcapita['PIB Per Capita (€)'] = (
    ppcapita['PIB Per Capita (€)']
    .str.replace('\xa0', '', regex=False)  
    .str.replace('.','', regex = False)
    .str.replace('€', '', regex = False)
)

ppcapita['Country'] = ppcapita['Country'].str.replace(' [+]','', regex = False)


# Cambiar tipo de datos con coerce para eliminar filas mal scrapeadas como nan
ppcapita['PIB Per Capita (€)'] = pd.to_numeric(ppcapita['PIB Per Capita (€)'], errors='coerce')
ppcapita.dropna(inplace=True)

# Cambiar tipo de datos
ppcapita[['Year', 'PIB Per Capita (€)']] = ppcapita[['Year', 'PIB Per Capita (€)']].astype(int)

ppcapita.head()

       Country  Year  PIB Per Capita (€)
0       España  2009               23140
1     Alemania  2009               30990
2  Reino Unido  2009               27920
3      Francia  2009               30040
4       Italia  2009               26600

### 1.6 Retail

In [200]:
# Cambiar tipo de datos de Customer ID a int64
retail['Customer ID'] = retail['Customer ID'].astype('Int64')

# Calcular % de ventas que salvamos al mantener nan en Customer ID
total_ventas = len(retail)
ventas_con_cliente = retail['Customer ID'].notna().sum()
ventas_sin_cliente = retail['Customer ID'].isna().sum()

porcentaje_recuperado = (ventas_sin_cliente * 100) / total_ventas

porcentaje_recuperado.round(2) # Esto nos permite salvar el 22,77% de las ventas

# Decidimos mantener los valores NaN en 'Customer ID' porque representan ventas reales
# sin cliente identificado. Sustituirlos por 0 crearía un cliente ficticio y distorsionaría
# análisis como segmentaciones, métricas por cliente o relaciones entre tablas.
# Usamos el tipo entero 'Int64', que permite NaN, para conservar la integridad del dato
# sin eliminar filas de ventas válidas ni introducir IDs artificiales.




# Imputar valor 'No description' en columna 'Description' sin descripcion
retail['Description'] = retail['Description'].fillna('No description')

In [201]:
# Convertimos 'InvoiceDate' a formato datetime para análisis temporales

retail['InvoiceDate'] = pd.to_datetime(retail['InvoiceDate'])

# Creamos una jerarquía de fechas que nos permitirá realizar análisis temporales
# detallados en el EDA y en el futuro dashboard:

retail['Year'] = retail['InvoiceDate'].dt.year # - Year: año de la transacción
retail['Month'] = retail['InvoiceDate'].dt.month # - Month: mes de la transacción
retail['Day'] = retail['InvoiceDate'].dt.day # - Day: día del mes
retail['Hour'] = retail['InvoiceDate'].dt.hour # - Hour: hora de la compra (útil para detectar patrones horarios)
retail['Week'] = retail['InvoiceDate'].dt.isocalendar().week # - Week: número de semana ISO (útil para análisis semanales)
retail['YearMonth'] = retail['InvoiceDate'].dt.to_period('M') # - YearMonth: período 'Año-Mes' para agrupar ventas mensuales de forma ordenada sin mezclar meses de distintos años y evitando problemas de ordenación.

retail.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Hour,Week,YearMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,2009,12,1,7,49,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,2009,12,1,7,49,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,2009,12,1,7,49,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,2009,12,1,7,49,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,2009,12,1,7,49,2009-12

In [202]:
# Eliminar duplicados
retail.drop_duplicates(inplace=True)
retail.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Hour,Week,YearMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,2009,12,1,7,49,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,2009,12,1,7,49,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,2009,12,1,7,49,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,2009,12,1,7,49,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,2009,12,1,7,49,2009-12

In [203]:
# Crear columna isCancelled
retail['isCancelled'] = retail['Invoice'].str.startswith('C')
retail.sample(15)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Hour,Week,YearMonth,isCancelled
69475,495543,84993a,75 GREEN PETIT FOUR CASES,1,2010-01-25 15:42:00,0.85,<NA>,United Kingdom,2010,1,25,15,4,2010-01,False
886925,568346,22811,SET OF 6 T-LIGHTS CACTI,1,2011-09-26 15:28:00,5.79,14096,United Kingdom,2011,9,26,15,39,2011-09,False
1021152,578317,23569,TRADTIONAL ALPHABET STAMP SET,4,2011-11-23 16:47:00,4.95,15398,United Kingdom,2011,11,23,16,47,2011-11,False
249386,513542,21564,PINK HEART SHAPE LOVE BUCKET,5,2010-06-25 11:57:00,2.95,16779,United Kingdom,2010,6,25,11,25,2010-06,False
703027,552134,22193,RED DINER WALL CLOCK,4,2011-05-06 11:50:00,8.50,14944,United Kingdom,2011,5,6,11,18,2011-05,False
720890,553718,22537,MAGIC DRAWING SLATE DINOSAUR,8,2011-05-18 16:14:00,0.83,<NA>,United Kingdom,2011,5,18,16,20,2011-05,False
126926,501523,21210,SET OF 72 RETRO SPOT PAPER DOILIES,12,2010-03-17 12:14:00,1.45,13612,United Kingdom,2010,3,17,12,11,2010-03,False
721598,553828,21673,WHITE SPOT BLUE CERAMIC DRAWER KNOB,24,2011-05-19 11:24:00,1.25,17865,United Kingdom,2011,5,19,11,20,2011-05,False
582128,541107,35651,VINTAGE BEAD PINK SCARF,12,2011-01-13 14:55:00,1.65,17744,United Kingdom,2011,1,13,14,2,2011-01,False
59822,494782,21379,CAMPHOR WOOD PORTOBELLO MUSHROOM,1,2010-01-18 13:15:00,2.51,<NA>,United Kingdom,2010,1,18,13,3,2010-01,False
671755,548984,84380,SET OF 3 BUTTERFLY COOKIE CUTTERS,2,2011-04-05 12:37:00,1.25,14546,United Kingdom,2011,4,5,12,14,2011-04,False
550801,538367,85124C,GREEN JUICY FRUIT PHOTO FRAME,6,2010-12-12 10:48:00,2.55,14800,United Kingdom,2010,12,12,10,49,2010-12,False
508959,536876,46776B,WOVEN BERRIES CUSHION COVER,1,2010-12-03 11:36:00,4.21,<NA>,United Kingdom,2010,12,3,11,48,2010-12,False
249406,513543,82494L,WOODEN FRAME ANTIQUE WHITE,24,2010-06-25 12:05:00,2.55,14648,United Kingdom,2010,6,25,12,25,2010-06,False
686585,550471,22333,RETROSPOT PARTY BAG + STICKER SET,1,2011-04-18 13:52:00,3.29,<NA>,United Kingdom,2011,4,18,13,16,2011-04,False

In [204]:
retail['Description'].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER     5740
REGENCY CAKESTAND 3 TIER               4295
No description                         4275
JUMBO BAG RED RETROSPOT                3388
ASSORTED COLOUR BIRD ORNAMENT          2868
PARTY BUNTING                          2730
STRAWBERRY CERAMIC TRINKET BOX         2534
LUNCH BAG  BLACK SKULL.                2447
JUMBO STORAGE BAG SUKI                 2387
JUMBO SHOPPER VINTAGE RED PAISLEY      2232
HEART OF WICKER SMALL                  2219
60 TEATIME FAIRY CAKE CASES            2193
LUNCH BAG SPACEBOY DESIGN              2149
BAKING SET 9 PIECE RETROSPOT           2135
LUNCH BAG CARS BLUE                    2134
WOODEN FRAME ANTIQUE WHITE             2125
HOME BUILDING BLOCK WORD               2107
NATURAL SLATE HEART CHALKBOARD         2090
PAPER CHAIN KIT 50'S CHRISTMAS         2084
POSTAGE                                2079
WOODEN PICTURE FRAME WHITE FINISH      2056
PACK OF 60 PINK PAISLEY CAKE CASES     2036
HEART OF WICKER LARGE                  2021
REX CASH+CARRY JUMBO SHOPPER           2006
LUNCH BAG WOODLAND                     1990
JUMBO  BAG BAROQUE BLACK WHITE         1927
VINTAGE SNAP CARDS                     1926
LUNCH BAG RED RETROSPOT                1910
JUMBO BAG STRAWBERRY                   1904
VICTORIAN GLASS HANGING T-LIGHT        1884
RED HANGING HEART T-LIGHT HOLDER       1828
6 RIBBONS RUSTIC CHARM                 1795
PACK OF 72 RETROSPOT CAKE CASES        1764
CHOCOLATE HOT WATER BOTTLE             1759
SCOTTIE DOG HOT WATER BOTTLE           1742
RECIPE BOX PANTRY YELLOW DESIGN        1742
LOVE BUILDING BLOCK WORD               1731
PLEASE ONE PERSON METAL SIGN           1664
JUMBO BAG PINK VINTAGE PAISLEY         1652
GIN + TONIC DIET METAL SIGN            1633
HOT WATER BOTTLE TEA AND SYMPATHY      1611
WOODLAND CHARLOTTE BAG                 1602
RECYCLING BAG RETROSPOT                1591
SWEETHEART CERAMIC TRINKET BOX         1583
RED TOADSTOOL LED NIGHT LIGHT          1578
HANGING HEART ZINC T-LIGHT HOLDER      1546
72 SWEETHEART FAIRY CAKE CASES         1509
PACK OF 72 SKULL CAKE CASES            1508
HANGING HEART JAR T-LIGHT HOLDER       1491
ROSES REGENCY TEACUP AND SAUCER        1486
SMALL POPCORN HOLDER                   1482
HAND OVER THE CHOCOLATE   SIGN         1480
JUMBO BAG PINK POLKADOT                1475
SET OF 3 CAKE TINS PANTRY DESIGN       1465
PAPER CHAIN KIT VINTAGE CHRISTMAS      1462
COOK WITH WINE METAL SIGN              1452
JUMBO BAG WOODLAND ANIMALS             1446
PACK OF 72 RETRO SPOT CAKE CASES       1445
ZINC METAL HEART DECORATION            1444
CHARLOTTE BAG SUKI DESIGN              1443
FELTCRAFT 6 FLOWER FRIENDS             1429
ROUND SNACK BOXES SET OF4 WOODLAND     1427
DOTCOM POSTAGE                         1423
PINK CREAM FELT CRAFT TRINKET BOX      1421
GREEN REGENCY TEACUP AND SAUCER        1413
ALARM CLOCK BAKELIKE RED               1413
STRAWBERRY CHARLOTTE BAG               1410
SPACEBOY LUNCH BOX                     1393
Manual                                 1392
DOLLY GIRL LUNCH BOX                   1370
BATHROOM METAL SIGN                    1358
RETROSPOT TEA SET CERAMIC 11 PC        1348
JUMBO STORAGE BAG SKULLS               1343
VINTAGE HEADS AND TAILS CARD GAME      1343
JUMBO BAG OWLS                         1337
PACK OF 60 DINOSAUR CAKE CASES         1333
PLASTERS IN TIN SPACEBOY               1332
LUNCH BAG PINK POLKADOT                1319
CREAM HEART CARD HOLDER                1318
VINTAGE UNION JACK BUNTING             1317
LUNCH BAG SUKI  DESIGN                 1313
ALARM CLOCK BAKELIKE GREEN             1310
COLOUR GLASS T-LIGHT HOLDER HANGING    1301
PLASTERS IN TIN WOODLAND ANIMALS       1301
RED RETROSPOT CAKE STAND               1297
RED RETROSPOT CHARLOTTE BAG            1295
SET OF 3 HEART COOKIE CUTTERS          1273
JUMBO BAG SPACEBOY DESIGN              1273
HAND WARMER OWL DESIGN                 1270
LUNCH BAG RED SPOTTY                   1260
JAM MAKING SET WITH JARS               1248
IVORY KITCHEN SCALES                   1244
PLASTERS IN TIN CIRCUS PARADE          1235
CLOTHES PEGS RETROSPOT PACK 24         1227
WOOD 2 DRAWER CABINET WHITE FINISH     1217
JAM MAKING SET PRINTED                 1217
HOT BATHS METAL SIGN                   1213
SET/5 RED RETROSPOT LID GLASS BOWLS    1210
SET/20 RED RETROSPOT PAPER NAPKINS     1206
WOOD BLACK BOARD ANT WHITE FINISH      1201
ROUND SNACK BOXES SET OF 4 FRUITS      1188
FELTCRAFT BUTTERFLY HEARTS             1184
EDWARDIAN PARASOL NATURAL              1177
LOVEBIRD HANGING DECORATION WHITE      1176
GUMBALL COAT RACK                      1176
PINK BLUE FELT CRAFT TRINKET BOX       1175
RED WOOLLY HOTTIE WHITE HEART.         1174
CHILLI LIGHTS                          1168
SPOTTY BUNTING                         1168
NO SINGING METAL SIGN                  1166
PLASTERS IN TIN VINTAGE PAISLEY        1165
WOODEN BOX OF DOMINOES                 1156
BOX OF 24 COCKTAIL PARASOLS            1156
SINGLE HEART ZINC T-LIGHT HOLDER       1155
POTTERING IN THE SHED METAL SIGN       1149
SMALL GLASS HEART TRINKET POT          1140
PACK OF 6 BIRDY GIFT TAGS              1138
HAND WARMER SCOTTY DOG DESIGN          1136
SET OF 3 BUTTERFLY COOKIE CUTTERS      1132
PACK OF 60 SPACEBOY CAKE CASES         1130
SET OF 20 VINTAGE CHRISTMAS NAPKINS    1128
LADIES & GENTLEMEN METAL SIGN          1127
WOOD S/3 CABINET ANT WHITE FINISH      1123
LUNCH BAG SUKI DESIGN                  1121
PLASTERS IN TIN SKULLS                 1119
ANTIQUE SILVER TEA GLASS ETCHED        1118
LUNCH BOX I LOVE LONDON                1118
SET OF 4 PANTRY JELLY MOULDS           1099
HAND WARMER BIRD DESIGN                1093
FAWN BLUE HOT WATER BOTTLE             1080
PINK REGENCY TEACUP AND SAUCER         1078
STRAWBERRY LUNCH BOX WITH CUTLERY      1072
60 CAKE CASES VINTAGE CHRISTMAS        1072
JUMBO BAG TOYS                         1070
LUNCH BAG APPLE DESIGN                 1066
RED  HARMONICA IN BOX                  1046
DOORMAT HEARTS                         1043
KNITTED UNION FLAG HOT WATER BOTTLE    1041
SPACEBOY BIRTHDAY CARD                 1039
WORLD WAR 2 GLIDERS ASSTD DESIGNS      1035
RED GINGHAM ROSE JEWELLERY BOX         1033
GREY HEART HOT WATER BOTTLE            1032
RABBIT NIGHT LIGHT                     1032
HOT WATER BOTTLE I AM SO POORLY        1029
SET OF 72 PINK HEART PAPER DOILIES     1026
METAL 4 HOOK HANGER FRENCH CHATEAU     1016
BAKING SET SPACEBOY DESIGN             1016
SMALL HEART MEASURING SPOONS           1015
LUNCH BAG DOLLY GIRL DESIGN            1015
ASSORTED COLOURS SILK FAN              1007
JUMBO BAG APPLES                       1007
DOORMAT UNION FLAG                     1005
ALARM CLOCK BAKELIKE PINK               998
CREAM SWEETHEART MINI CHEST             997
PARTY METAL SIGN                        995
SET/6 RED SPOTTY PAPER PLATES           995
HEART IVORY TRELLIS SMALL               995
BEWARE OF THE CAT METAL SIGN            990
CHOCOLATE THIS WAY METAL SIGN           987
BLUE HARMONICA IN BOX                   981
RIBBON REEL STRIPES DESIGN              980
PLASTERS IN TIN STRONGMAN               979
RED KITCHEN SCALES                      979
PACK OF 60 MUSHROOM CAKE CASES          969
EDWARDIAN PARASOL BLACK                 968
SET/20 RED SPOTTY PAPER NAPKINS         962
HANGING JAM JAR T-LIGHT HOLDER          961
RED RETROSPOT PICNIC BAG                960
RETROSPOT HEART HOT WATER BOTTLE        959
WHITE SKULL HOT WATER BOTTLE            956
PICNIC BASKET WICKER SMALL              950
CHARLOTTE BAG PINK POLKADOT             943
SET/5 RED SPOTTY LID GLASS BOWLS        941
GRAND CHOCOLATECANDLE                   939
WHITE WOOD GARDEN PLANT LADDER          937
PACK OF 12 HEARTS DESIGN TISSUES        935
PAPER BUNTING RETROSPOT                 935
WOODEN SCHOOL COLOURING SET             934
GARDENERS KNEELING PAD KEEP CALM        931
TOILET METAL SIGN                       930
RED SPOTTY BISCUIT TIN                  929
CERAMIC STRAWBERRY CAKE MONEY BANK      928
SUKI  SHOULDER BAG                      926
JUMBO BAG ALPHABET                      925
POTTING SHED TEA MUG                    917
MEMO BOARD RETROSPOT  DESIGN            915
SCANDINAVIAN REDS RIBBONS               914
SET OF 3 REGENCY CAKE TINS              913
DOORMAT RED RETROSPOT                   910
HAND WARMER UNION JACK                  909
JUMBO BAG SCANDINAVIAN PAISLEY          903
LUNCH BOX WITH CUTLERY RETROSPOT        902
HEART FILIGREE DOVE  SMALL              901
TRADITIONAL KNITTING NANCY              899
PINK HAPPY BIRTHDAY BUNTING             898
METAL SIGN TAKE IT OR LEAVE IT          894
TEA TIME PARTY BUNTING                  892
JUMBO BAG VINTAGE LEAF                  892
NATURAL SLATE CHALKBOARD LARGE          889
FELTCRAFT CUSHION OWL                   888
CHICK GREY HOT WATER BOTTLE             880
WICKER STAR                             878
PAPER BUNTING WHITE LACE                876
TRADITIONAL WOODEN SKIPPING ROPE        875
CREAM CUPID HEARTS COAT HANGER          865
CHILDRENS APRON SPACEBOY DESIGN         865
4 TRADITIONAL SPINNING TOPS             862
WOODEN HEART CHRISTMAS SCANDINAVIAN     861
SET OF 6 SPICE TINS PANTRY DESIGN       861
POPCORN HOLDER                          861
PACK OF 20 NAPKINS PANTRY DESIGN        860
SET/6 RED SPOTTY PAPER CUPS             858
RED RETROSPOT SMALL MILK JUG            858
HEART IVORY TRELLIS LARGE               857
12 PENCILS SMALL TUBE SKULL             857
TRAVEL SEWING KIT                       857
FOUR HOOK  WHITE LOVEBIRDS              855
TEA PARTY BIRTHDAY CARD                 854
KEY FOB , SHED                          853
TRADITIONAL WOODEN CATCH CUP GAME       850
RED STRIPE CERAMIC DRAWER KNOB          845
PACK OF 12 LONDON TISSUES               845
LUNCH BAG PINK RETROSPOT                841
BINGO SET                               840
SET/3 RED GINGHAM ROSE STORAGE BOX      839
PINK FAIRY CAKE CHILDRENS APRON         837
VINTAGE SNAKES & LADDERS                835
WHITE SPOT RED CERAMIC DRAWER KNOB      835
3 STRIPEY MICE FELTCRAFT                833
BLUE STRIPE CERAMIC DRAWER KNOB         832
COLOUR GLASS. STAR T-LIGHT HOLDER       831
FELTCRAFT DOLL MOLLY                    829
NATURAL SLATE RECTANGLE CHALKBOARD      828
ENAMEL FLOWER JUG CREAM                 828
PAPER CHAIN KIT EMPIRE                  825
LARGE HEART MEASURING SPOONS            824
HANGING METAL HEART LANTERN             824
DOORMAT NEW ENGLAND                     824
SET OF 36 TEATIME PAPER DOILIES         822
SET OF 36 PAISLEY FLOWER DOILIES        821
PAPER CHAIN KIT RETROSPOT               821
JUMBO BAG PINK WITH WHITE SPOTS         819
FELTCRAFT CUSHION RABBIT                816
SET OF 3 NOTEBOOKS IN PARCEL            815
SAVE THE PLANET MUG                     811
AREA PATROLLED METAL SIGN               810
SET OF 20 KIDS COOKIE CUTTERS           809
RETRO SPOT TEA SET CERAMIC 11 PC        805
SET 12 KIDS COLOUR  CHALK STICKS        804
PACK OF 12 TRADITIONAL CRAYONS          804
WOODEN STAR CHRISTMAS SCANDINAVIAN      804
HOT WATER BOTTLE KEEP CALM              804
WASHROOM METAL SIGN                     803
PICNIC BASKET WICKER LARGE              803
RED SPOTTY CHARLOTTE BAG                802
FELTCRAFT DOLL ROSIE                    801
PAPER BUNTING RETRO SPOTS               798
FELTCRAFT CUSHION BUTTERFLY             798
YOU'RE CONFUSING ME METAL SIGN          793
ROTATING SILVER ANGELS T-LIGHT HLDR     787
WOODEN UNION JACK BUNTING               782
BLUE SPOT CERAMIC DRAWER KNOB           781
I'M ON HOLIDAY METAL SIGN               781
ASSORTED COLOUR MINI CASES              780
HOME SWEET HOME MUG                     780
SET OF 6 RIBBONS VINTAGE CHRISTMAS      778
WHITE SPOT BLUE CERAMIC DRAWER KNOB     777
GARDENERS KNEELING PAD CUP OF TEA       773
STRAWBERRY SHOPPER BAG                  770
SILVER HANGING T-LIGHT HOLDER           769
HAND WARMER RED RETROSPOT               769
LUNCH BAG ALPHABET DESIGN               769
ENAMEL BREAD BIN CREAM                  768
MINI CAKE STAND  HANGING STRAWBERY      767
MEMO BOARD COTTAGE DESIGN               763
ALARM CLOCK BAKELIKE IVORY              763
TEA TIME OVEN GLOVE                     761
LAUNDRY 15C METAL SIGN                  759
CERAMIC HEART FAIRY CAKE MONEY BANK     759
TRADITIONAL MODELLING CLAY              758
SET/20 STRAWBERRY PAPER NAPKINS         756
POPPY'S PLAYHOUSE KITCHEN               756
WOODEN ROUNDERS GARDEN SET              755
PAINTED METAL PEARS ASSORTED            751
RED SPOT CERAMIC DRAWER KNOB            750
DOORMAT SPOTTY HOME SWEET HOME          750
GINGERBREAD MAN COOKIE CUTTER           749
3 HEARTS HANGING DECORATION RUSTIC      747
PINK DOUGHNUT TRINKET POT               746
PACK 20 ENGLISH ROSE PAPER NAPKINS      744
PLACE SETTING WHITE HEART               743
SMALL DOLLY MIX DESIGN ORANGE BOWL      743
DOORMAT KEEP CALM AND COME IN           739
TRADITIONAL CHRISTMAS RIBBONS           737
WHITE METAL LANTERN                     737
FAMILY ALBUM WHITE PICTURE FRAME        736
PINK HEART SHAPE EGG FRYING PAN         735
PACK OF 12 SUKI TISSUES                 734
RECIPE BOX BLUE SKETCHBOOK DESIGN       731
JUMBO BAG VINTAGE DOILY                 731
SET 12 RETRO WHITE CHALK STICKS         730
SKULL SHOULDER BAG                      729
JUMBO BAG 50'S CHRISTMAS                729
HEART FILIGREE DOVE LARGE               728
HOME SWEET HOME METAL SIGN              728
MINI PAINT SET VINTAGE                  728
EDWARDIAN PARASOL RED                   725
SET 7 BABUSHKA NESTING BOXES            725
PICTURE DOMINOES                        723
CHRISTMAS CRAFT LITTLE FRIENDS          721
SET OF 6 SOLDIER SKITTLES               720
SKULL LUNCH BOX WITH CUTLERY            719
DOORMAT FANCY FONT HOME SWEET HOME      718
HOMEMADE JAM SCENTED CANDLES            717
ZINC FOLKART SLEIGH BELLS               716
FOOD CONTAINER SET 3 LOVE HEART         715
POPPY'S PLAYHOUSE BEDROOM               715
ANTIQUE SILVER T-LIGHT GLASS            715
KITCHEN METAL SIGN                      714
KEY FOB , BACK DOOR                     713
IVORY HANGING DECORATION  HEART         712
DOORSTOP RETROSPOT HEART                712
RECIPE BOX RETROSPOT                    712
ANTIQUE SILVER TEA GLASS ENGRAVED       710
AIRLINE BAG VINTAGE TOKYO 78            706
RED RETROSPOT SHOPPER BAG               705
BLUE HAPPY BIRTHDAY BUNTING             700
TOY TIDY SPACEBOY                       700
FELTCRAFT PRINCESS CHARLOTTE DOLL       697
SWALLOWS GREETING CARD                  696
RIBBON REEL HEARTS DESIGN               695
JUMBO BAG DOLLY GIRL DESIGN             694
3 HOOK PHOTO SHELF ANTIQUE WHITE        693
MULTI COLOUR SILVER T-LIGHT HOLDER      692
12 PENCIL SMALL TUBE WOODLAND           683
LUNCH BAG VINTAGE LEAF DESIGN           681
CIRCUS PARADE LUNCH BOX                 680
DOOR MAT UNION FLAG                     678
COLOURING PENCILS BROWN TUBE            675
STRAWBERRY   PICNIC BAG                 675
ROUND SNACK BOXES SET OF 4 SKULLS       675
MINT KITCHEN SCALES                     675
COFFEE MUG CAT + BIRD DESIGN            674
VICTORIAN SEWING BOX SMALL              673
JUMBO BAG SCANDINAVIAN BLUE PAISLEY     672
CHARLIE+LOLA PINK HOT WATER BOTTLE      671
FANCY FONT BIRTHDAY CARD,               671
FELTCRAFT DOLL EMILY                    669
FULL ENGLISH BREAKFAST PLATE            668
PACK OF 20 SKULL PAPER NAPKINS          665
AGED GLASS SILVER T-LIGHT HOLDER        665
PHOTO FRAME CORNICE                     665
VINTAGE PAISLEY STATIONERY SET          663
WOODEN HAPPY BIRTHDAY GARLAND           662
SCANDINAVIAN PAISLEY PICNIC BAG         657
WOODEN CROQUET GARDEN SET               657
OPEN CLOSED METAL SIGN                  656
FELTCRAFT PRINCESS LOLA DOLL            655
I CAN ONLY PLEASE ONE PERSON MUG        652
ENAMEL MEASURING JUG CREAM              652
RETROSPOT CHILDRENS APRON               651
VINTAGE UNION JACK CUSHION COVER        649
BALLOONS  WRITING SET                   649
SMALL WHITE HEART OF WICKER             648
FOLKART ZINC HEART CHRISTMAS DEC        647
ZINC WILLIE WINKIE  CANDLE STICK        646
SET OF 60 PANTRY DESIGN CAKE CASES      646
RED RETROSPOT TRADITIONAL TEAPOT        645
CHARLOTTE BAG DOLLY GIRL DESIGN         644
BLACK RECORD COVER FRAME                643
POTTERING MUG                           640
ENGLISH ROSE NOTEBOOK A7 SIZE           639
PINK VINTAGE PAISLEY PICNIC BAG         639
ALARM CLOCK BAKELIKE ORANGE             639
ROBOT BIRTHDAY CARD                     636
WATERING CAN BLUE ELEPHANT              635
RED DINER WALL CLOCK                    634
CERAMIC CHERRY CAKE MONEY BANK          634
GINGHAM HEART  DOORSTOP RED             632
PAPER BUNTING COLOURED LACE             631
COWBOYS AND INDIANS BIRTHDAY CARD       631
PIGGY BANK RETROSPOT                    630
GLITTER BUTTERFLY CLIPS                 629
GIN AND TONIC MUG                       629
DELUXE SEWING KIT                       627
RED RETROSPOT PEG BAG                   625
SMALL MARSHMALLOWS PINK BOWL            624
60 CAKE CASES DOLLY GIRL DESIGN         624
KINGS CHOICE TEA CADDY                  623
CHRISTMAS TOILET ROLL                   622
HEART DECORATION WITH PEARLS            621
FAIRY CAKE FLANNEL ASSORTED COLOUR      619
LUNCH BAG VINTAGE DOILY                 619
RED FLORAL FELTCRAFT SHOULDER BAG       617
HAND WARMER BABUSHKA DESIGN             616
LARGE POPCORN HOLDER                    615
DOORMAT WELCOME TO OUR HOME             615
SET OF 72 RETROSPOT PAPER  DOILIES      615
ROUND CONTAINER SET OF 5 RETROSPOT      614
CANDLEHOLDER PINK HANGING HEART         614
CHARLIE + LOLA RED HOT WATER BOTTLE     612
FILIGRIS HEART WITH BUTTERFLY           609
RED RETROSPOT SUGAR JAM BOWL            607
DOORMAT FAIRY CAKE                      605
FELTCRAFT CHRISTMAS FAIRY               605
JUMBO BAG PEARS                         604
TOY TIDY PINK POLKADOT                  603
PICTURE FRAME WOOD TRIPLE PORTRAIT      602
PAPER CHAIN KIT RETRO SPOT              601
MAGIC DRAWING SLATE SPACEBOY            601
10 COLOUR SPACEBOY PEN                  599
CHARLOTTE BAG APPLES DESIGN             594
12 PENCILS TALL TUBE SKULLS             591
SLEEPING CAT ERASERS                    588
BATH BUILDING BLOCK WORD                587
CHRISTMAS CRAFT TREE TOP ANGEL          586
BAG 125g SWIRLY MARBLES                 586
LARGE CAKE STAND  HANGING STRAWBERY     585
PINK BABY BUNTING                       585
LARGE WHITE HEART OF WICKER             582
FLORAL FOLK STATIONERY SET              581
CHOCOLATE BOX RIBBONS                   581
BAG 250g SWIRLY MARBLES                 581
GLASS  BEURRE DISH                      581
PACK OF 6 PANNETONE GIFT BOXES          581
BOX OF VINTAGE ALPHABET BLOCKS          580
PINK FLORAL FELTCRAFT SHOULDER BAG      579
RED RETROSPOT OVEN GLOVE                579
RED RETROSPOT BUTTER DISH               577
JUMBO BAG CHARLIE AND LOLA TOYS         575
POPPY'S PLAYHOUSE LIVINGROOM            573
15CM CHRISTMAS GLASS BALL 20 LIGHTS     572
WOODEN TREE CHRISTMAS SCANDINAVIAN      572
ALARM CLOCK BAKELIKE CHOCOLATE          572
VICTORIAN SEWING BOX LARGE              571
CERAMIC CAKE DESIGN SPOTTED MUG         570
BLACK HEART CARD HOLDER                 570
COFFEE MUG APPLES DESIGN                568
PHOTO CUBE                              567
36 PENCILS TUBE SKULLS                  567
PACK OF 12 WOODLAND TISSUES             566
SWEETHEART CAKESTAND 3 TIER             566
RECORD FRAME 7" SINGLE SIZE             565
PAPER BUNTING VINTAGE PAISLEY           564
GARDENERS KNEELING PAD                  564
DINOSAURS  WRITING SET                  563
RIBBON REEL CHRISTMAS SOCK BAUBLE       563
S/6 WOODEN SKITTLES IN COTTON BAG       561
SET OF 72 RETRO SPOT PAPER  DOILIES     560
BLUE DINER WALL CLOCK                   560
SET OF 12 FAIRY CAKE BAKING CASES       559
METAL SIGN,CUPCAKE SINGLE HOOK          558
GIN & TONIC DIET GREETING CARD          557
RED RETROSPOT BOWL                      555

In [205]:
# Estandarizar la columna Description a minúsculas y limpiar espacios
retail['Description'] = (
    retail['Description']
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [206]:
# Solo nos interesan las ventas realizadas y canceladas, no los movimientos internos del almacen
# Por ello todas aquellas lineas que tengan de precio 0 y cantidad 0 no son ventas y debemos filtrar para que no aparezcan

# 2. Filtrar ventas reales
ventas_reales = retail[
    (retail['Price'] != 0) &                 # Precio mayor que 0
    (retail['Quantity'] != 0) &              # Cantidad mayor que 0
    (retail['Customer ID'].notna()) &        # Cliente identificado
    (~retail['StockCode'].isin(['POST', 'M']))  # Excluir envíos (POST) y ajustes manuales (M)
]

ventas_reales.info()

<class 'pandas.DataFrame'>
Index: 794754 entries, 0 to 1067369
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      794754 non-null  str
 1   StockCode    794754 non-null  str
 2   Description  794754 non-null  str
 3   Quantity     794754 non-null  int64
 4   InvoiceDate  794754 non-null  datetime64[us]
 5   Price        794754 non-null  float64
 6   Customer ID  794754 non-null  Int64
 7   Country      794754 non-null  str
 8   Year         794754 non-null  int32
 9   Month        794754 non-null  int32
 10  Day          794754 non-null  int32
 11  Hour         794754 non-null  int32
 12  Week         794754 non-null  UInt32
 13  YearMonth    794754 non-null  period[M]
 14  isCancelled  794754 non-null  bool
dtypes: Int64(1), UInt32(1), bool(1), datetime64[us](1), float64(1), int32(4), int64(1), period[M](1), str(4)
memory usage: 78.1 MB

##  2. Traducir paises de ventas_reales para hacer un posterior merge correcto

In [207]:
pd.set_option('display.max_rows', None)
list(ventas_reales['Country'].unique())

['United Kingdom',
 'France',
 'Australia',
 'EIRE',
 'Germany',
 'Portugal',
 'Japan',
 'Denmark',
 'Netherlands',
 'Poland',
 'Spain',
 'Channel Islands',
 'Italy',
 'Cyprus',
 'Belgium',
 'Greece',
 'Norway',
 'Austria',
 'Sweden',
 'United Arab Emirates',
 'Finland',
 'Switzerland',
 'USA',
 'Unspecified',
 'Nigeria',
 'Malta',
 'RSA',
 'Singapore',
 'Bahrain',
 'Thailand',
 'Israel',
 'Lithuania',
 'West Indies',
 'Korea',
 'Brazil',
 'Canada',
 'Iceland',
 'Lebanon',
 'Saudi Arabia',
 'Czech Republic',
 'European Community']

In [208]:
# 1. Traducir ventas_reales con paro
traduccion_paises = {
    'España': 'Spain',
    'Alemania': 'Germany',
    'Reino Unido': 'United Kingdom',
    'Francia': 'France',
    'Italia': 'Italy',
    'Portugal': 'Portugal',
    'Estados Unidos': 'USA',
    'Japón': 'Japan',
    'Australia': 'Australia',
    'Bélgica': 'Belgium',
    'Canadá': 'Canada',
    'Dinamarca': 'Denmark',
    'Países Bajos': 'Netherlands',
    'Polonia': 'Poland',
    'Chipre': 'Cyprus',
    'Grecia': 'Greece',
    'Noruega': 'Norway',
    'Austria': 'Austria',
    'Suecia': 'Sweden',
    'Emiratos Árabes Unidos': 'United Arab Emirates',
    'Finlandia': 'Finland',
    'Suiza': 'Switzerland',
    'Nigeria': 'Nigeria',
    'Malta': 'Malta',
    'Singapur': 'Singapore',
    'Baréin': 'Bahrain',
    'Tailandia': 'Thailand',
    'Israel': 'Israel',
    'Lituania': 'Lithuania',
    'Brasil': 'Brazil',
    'Islandia': 'Iceland',
    'Líbano': 'Lebanon',
    'Arabia Saudita': 'Saudi Arabia',
    'Chequia': 'Czech Republic',
    
    # Casos especiales
    'Irlanda': 'EIRE',
    'Sudáfrica': 'RSA',
    'Corea del Sur': 'Korea'
}

# Traduciendo los valores

for df in [deuda, paro, pib, poblacion, ppcapita]:
    df['Country'] = df['Country'].replace(traduccion_paises)

ppcapita.sample(20)

                      Country  Year  PIB Per Capita (€)
418                  Barbados  2011               14246
85                       Irak  2009                2657
384                   Uruguay  2010                9756
200            United Kingdom  2010               29830
381                  Tanzania  2010                 560
172                      Togo  2009                 517
93                   Kiribati  2009                1012
63                       Fiyi  2009                2643
306                Luxemburgo  2010               83550
139                    Panamá  2009                5541
132                 Nicaragua  2009                1037
455                    Egipto  2011                2211
316                      Malí  2010                 588
441                   Camerún  2011                1088
526                     Níger  2011                 368
40   República Centroafricana  2009                 322
157                    Sweden  2009               33670
567                      Chad  2011                 970
219      Bosnia y Herzegovina  2010                3660
143                  Pakistán  2009                 796

## 3. Exportar dataframes a la carpeta 2_cleaned

In [209]:
lista = [
    ('deuda', deuda),
    ('paro', paro),
    ('pib', pib),
    ('poblacion', poblacion),
    ('ppcapita', ppcapita),
    ('ventas', ventas_reales)
]

for nombre, df in lista:
    df.to_csv(f"../Data/2_cleaned/{nombre}.csv", index=False)